s = open('filename.xml').read()
s = s.replace('""' , '"')
s = s.replace('&' , '&amp;')
s = s.replace('&amp;&amp;' , '&amp;')
s = s.replace('&amp;#x' , '&#x')
s = s.replace('&amp;lt;br&amp;gt;' , '&lt;br&gt;')
s = s.replace('extent>"' , 'extent>')
s = s.replace('"</extent>' , '</extent>')
s = s.replace('Summary">"' , 'Summary">')
s = s.replace('"</abstract>' , '</abstract>')
s = s.replace('<abstract>"' , '<abstract>')
s = s.replace('<note>"' , '<note>')
s = s.replace('"</note>' , '</note>')
s = s.replace('<note type="biographical">"' , '<note type="biographical">')
s = s.replace('<namePart>"' , '<namePart>')
s = s.replace('"</namePart>' , '</namePart>')
s = s.replace('marcrelator">"' , 'marcrelator">')
s = s.replace('"</roleTerm>' , '</roleTerm>')
s = s.replace('typeOfResource>"' , 'typeOfResource>')
s = s.replace('"</typeOfResource>' , '</typeOfResource>')
s = s.replace('authority="gmgpc">"' , 'authority="gmgpc">')
s = s.replace('authority="aat">"' , 'authority="aat">')
s = s.replace('authority="tgm">"' , 'authority="tgm">')
s = s.replace('authority="lctgm">"' , 'authority="lctgm">')
s = s.replace('authority="lcgft">"' , 'authority="lcgft">')
s = s.replace('authority="migfg">"' , 'authority="migfg">')
s = s.replace('"</genre>' , '</genre>')
s = s.replace('<topic>"' , '<topic>')
s = s.replace('"</topic>' , '</topic>')
s = s.replace('<genre>"' , '<genre>')
s = s.replace('<name>"' , '<name>')
s = s.replace('"</name>' , '</name>')
s = s.replace('<geographic>"' , '<geographic>')
s = s.replace('"</geographic>' , '</geographic>')
s = s.replace('<temporal>"' , '<temporal>')
s = s.replace('"</temporal>' , '</temporal>')
s = s.replace('"</physicalLocation>' , '</physicalLocation>')
s = s.replace('<physicalLocation>"' , '<physicalLocation>')
s = s.replace('<url note="Finding aid">"' , '<url note="Finding aid">')
s = s.replace('"</url>' , '</url>')
s = s.replace('encoding="w3cdtf">"' , 'encoding="w3cdtf">')
s = s.replace('encoding="edtf">"' , 'encoding="edtf">')
s = s.replace('"</dateCreated>' , '</dateCreated>')
s = s.replace('"</dateCaptured>' , '</dateCaptured>')
s = s.replace('"</dateIssued>' , '</dateIssued>')
s = s.replace('<dateIssued>"' , '<dateIssued>')
s = s.replace('<copyrightDate>"' , '<copyrightDate>')
s = s.replace('"</copyrightDate>' , '</copyrightDate>')
s = s.replace('Image quality">"' , 'Image quality">')
s = s.replace('Hagley ID">"' , 'Hagley ID">')
s = s.replace('title>"' , 'title>')
s = s.replace('"</title>' , '</title>')
s = s.replace('<internetMediaType>"' , '<internetMediaType>')
s = s.replace('"</internetMediaType>' , '</internetMediaType>')
s = s.replace('"</identifier>' , '</identifier>')
s = s.replace('<shelfLocator>"' , '<shelfLocator>')
s = s.replace('"</shelfLocator>' , '</shelfLocator>')
s = s.replace('<placeTerm>"' , '<placeTerm>')
s = s.replace('"</placeTerm>' , '</placeTerm>')
s = s.replace('<publisher>"' , '<publisher>')
s = s.replace('"</publisher>' , '</publisher>')
s = s.replace('<issuance>"' , '<issuance>')
s = s.replace('"</issuance>' , '</issuance>')
s = s.replace('<frequency>"' , '<frequency>')
s = s.replace('"</frequency>' , '</frequency>')
s = s.replace('<edition>"' , '<edition>')
s = s.replace('"</edition>' , '</edition>')
s = s.replace('<number>"' , '<number>')
s = s.replace('"</number>' , '</number>')
s = s.replace('<digitalOrigin>"' , '<digitalOrigin>')
s = s.replace('"</digitalOrigin>' , '</digitalOrigin>')
s = s.replace('<reformattingQuality>"' , '<reformattingQuality>')
s = s.replace('"</reformattingQuality>' , '</reformattingQuality>')
s = s.replace('<note type="Digital File Characteristics">"' , '<note type="Digital File Characteristics">')
s = s.replace('Box/folder number, "' , 'Box/folder number, ')
s = s.replace('Hagley Museum and Library"' , 'Hagley Museum and Library')
s = s.replace('", "Audiovisual Collections' , ', Audiovisual Collections')
s = s.replace('", "Manuscripts and Archives' , ', Manuscripts and Archives')
s = s.replace('", "Published Collections' , ', Published Collections')
s = s.replace(', "Audiovisual Collections' , ', Audiovisual Collections')
s = s.replace(', "Manuscripts and Archives' , ', Manuscripts and Archives')
s = s.replace(', "Published Collections' , ', Published Collections')
s = s.replace('", Audiovisual Collections' , ', Audiovisual Collections')
s = s.replace('", Manuscripts and Archives' , ', Manuscripts and Archives')
s = s.replace('", Published Collections' , ', Published Collections')
s = s.replace('type="text">"' , 'type="text">')
s = s.replace('type="code">"' , 'type="code">')
s = s.replace('"</languageTerm>' , '</languageTerm>')
print(s)